# The URL the site will be built for
base_url = "https://joaohlc.dev.br/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Custom theme
theme = "duckquill"

default_language = "pt"

# Settings
author = "João H. L. Corrêa"
minify_html = true

title = "João H. L. Corrêa"

[markdown]
smart_punctuation = true
bottom_footnotes = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
accent_color = "#04E762"
styles=["custom.css"]
show_copy_button = true
issues_url = "https://github.com/jhenriquelc/site-pessoal/issues"
source_url = "https://github.com/jhenriquelc/site-pessoal"
default_theme = "dark"

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the Atom/RSS feed button in the nav
show_feed = true
# Whether to show the link to the source repository in the nav
show_repo = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
	# { name = "Links", menu = [
	# 	{ url = "@/blog/_index.md", name = "Blog" },
	# 	{ url = "@/demo/index.md", name = "Demo" },
	# 	{ url = "@/mods/index.md", name = "Mods" }
	# ] },
	{ url = "https://linkedin.com/in/joaohlc", name = "LinkedIn" },
	{ url = "https://github.com/jhenriquelc", name = "GitHub" }
]


[extra.footer]
show_copyright = true
copyright = "© João H. L. Corrêa, 2026 -- Licenciada nos termos da EUPL"
# Whether to show "Powered by Zola and Duckquill"
show_powered_by = true
# Whether to show link to website source
show_source = false
emoji_favicon = "🧑🏽‍💻"
